"""money update

Revision ID: a6008fccaf21
Revises: b39037fe1f89
Create Date: 2019-10-18 22:53:28.043651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6008fccaf21'
down_revision = 'b39037fe1f89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_income2_timestamp', table_name='income2')
    op.drop_table('income2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('income2',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('value', sa.FLOAT(), nullable=True),
    sa.Column('note', sa.VARCHAR(length=150), nullable=True),
    sa.Column('category', sa.VARCHAR(length=150), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_income2_timestamp', 'income2', ['timestamp'], unique=False)
    # ### end Alembic commands ###
